### ISSUE TITLE
ModuleNotFoundError: No module named 'update_res_app'

### ISSUE THREAD

**Issue by 308066400** [zlgopen/awtk-go#2]
执行python ./scripts/update_res.py all出错，提示：

Traceback (most recent call last):
  File "D:\OneDrive\桌面\awtk-go\scripts\update_res.py", line 41, in <module>
    update_res(ARGUMENTS, is_new_usage)
  File "D:\OneDrive\桌面\awtk-go\scripts\update_res.py", line 27, in update_res
    import update_res_app as updater
ModuleNotFoundError: No module named 'update_res_app'

**Comment by xianjimli** [comment]
awtk放在哪个位置的

**Comment by 308066400** [comment]
@xianjimli 
是你的https://github.com/zlgopen/awtk-go/scripts目录下的py文件没有定义update_res_app啊。。。错误提示很清楚了
你的update_res_app定义在https://github.com/zlgopen/awtk项目中的scripts/update_res.py文件内。
python文件不可能包含到其他项目的py文件吧。
好乱，建议你不要在自己开发环境下测试，重新按照你项目文档在新的机器或虚拟机上做一次验证。
我意思是项目说明文档对不上。

**Comment by xianjimli** [comment]
这一步你做了吗：
>修改环境变量 (MacOS/Linux/Windows(bash) 下修改 env.sh)，将 AWTK_ROOT 指向 awtk 的根目录，并使其生效。

**Comment by xianjimli** [comment]
env.sh

```
#Linux/MasOS
export AWTK_ROOT=${PWD}/../awtk

#windows bash
#export AWTK_ROOT=d:/work/awtk-root/awtk

export PATH=${PATH}:${AWTK_ROOT}/bin
export LD_LIBRARY_PATH=${AWTK_ROOT}/bin

export CGO_CFLAGS="-DWITH_FS_RES=1 -DAWTK_GO=1 -DHAS_STDIO=1"
export CGO_CFLAGS="${CGO_CFLAGS} -I ${AWTK_ROOT}/src"
export CGO_CFLAGS="${CGO_CFLAGS} -I ${AWTK_ROOT}/3rd"
export CGO_CFLAGS="${CGO_CFLAGS} -I ${AWTK_ROOT}/src/ext_widgets"
export CGO_LDFLAGS="-L ${AWTK_ROOT}/bin -lawtk"

#for window mingw, uncomment this following line
#export CGO_CFLAGS="${CGO_CFLAGS} -DMINGW=1"
```

指向你自己机器上AWTK的位置。
```
export AWTK_ROOT=d:/work/awtk-root/awtk
```
